language: go
os: linux
go:
- 1.14.x
env:
  global:
  - GO111MODULE=on
script:
- go test ./...
- go build -ldflags "-X fops/cmd/subcmd/version.version=$(git describe --tags `git
  rev-list --tags --max-count=1`)" -o fops
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  file: fops
  on:
    tags: true
    repo: tsunejui/fops
notifications:
  email:
    on_success: never
